Trabalhando com arrays Numpy

In [2]:
import numpy as np
import os

Carregando arquivos txt

In [3]:
file_name1 = os.path.join('./data/', "carros-km.txt")
km = np.loadtxt(file_name1, dtype=int)
print(km)

[ 44410   5712  37123      0  25757  10728      0  77599  99197  37978
  12859   8052  89773      0  41457 115607  46449      0  37086  15173
 101193      0  98079 102959      0      0   5795      0  58848  94381
  30163  53332  17720  33808  90684  43975      0      0   5526      0
  93415  40762      0  86302      0   9755  69945   2395      0  80349
  85554  50496  67716  93947  35345  81007 119513      0      0      0
      0      0 118895  48509 100912  95649      0  90495      0  29132
  23802  84992  54395  26731  44329 118236 113808    610      0      0
  12887  79607  90924  42733      0      0 117714 113885      0  30511
  74867 119760   8356  64247  88661   4539 110116  33215  92001      0
  81708  70641      0  91277  26544  52596  47503  89056  28834 110564
  56638  17357  74015  15196      0  10821      0      0   9595  99052
  52389 119945  96005  31639      0  80187      0  58212  61672  32017
      0  56944      0  86519   4821 101025  30705      0  32555 103389
      

In [4]:
file_name2 = os.path.join('./data/', "carros-anos.txt")
anos = np.loadtxt(file_name2, dtype=int)
print(anos)


[2003 1991 1990 2019 2006 2012 2019 2009 2010 2011 2002 2007 2001 2019
 2009 2016 2012 2019 2016 2017 2002 2019 1994 1991 2019 2019 2016 2019
 2002 1991 1997 1995 2018 1991 2014 1995 2019 2019 2009 2019 2013 2003
 2019 2002 2019 2002 2004 2001 2019 2003 2009 2006 2000 2006 2010 1994
 2007 2019 2019 2019 2019 2019 2017 2011 2001 1996 2019 1994 2019 2007
 1994 2007 1997 2006 2013 1994 2008 2008 2019 2019 1999 2007 1993 1995
 2019 2019 2016 2011 2019 2002 2013 2017 2016 2008 2018 2003 2003 2004
 2010 2019 2006 2001 2019 2015 2018 2017 1992 2001 1993 1995 2003 2014
 2008 2013 2019 2017 2019 2019 2006 2015 2007 2005 2017 1998 2019 1999
 2019 2009 2003 1994 2019 1994 2019 2015 1996 1997 1993 2019 1992 1995
 2019 1990 2019 2019 1991 1990 2012 2007 2013 2000 2002 1996 1996 2015
 1993 2013 2013 2009 2019 2019 2002 1997 1998 2004 1996 2015 2016 2005
 1999 1995 1993 2004 2013 1998 2018 2019 2018 2019 1990 2009 1990 2006
 2002 1991 1992 2019 2019 2005 2010 2019 2016 2019 2010 1994 2001 2014
 1996 

Percorrendo o numpy

In [5]:
for i in range(len(km)):
    print(km[i], anos[i])

44410 2003
5712 1991
37123 1990
0 2019
25757 2006
10728 2012
0 2019
77599 2009
99197 2010
37978 2011
12859 2002
8052 2007
89773 2001
0 2019
41457 2009
115607 2016
46449 2012
0 2019
37086 2016
15173 2017
101193 2002
0 2019
98079 1994
102959 1991
0 2019
0 2019
5795 2016
0 2019
58848 2002
94381 1991
30163 1997
53332 1995
17720 2018
33808 1991
90684 2014
43975 1995
0 2019
0 2019
5526 2009
0 2019
93415 2013
40762 2003
0 2019
86302 2002
0 2019
9755 2002
69945 2004
2395 2001
0 2019
80349 2003
85554 2009
50496 2006
67716 2000
93947 2006
35345 2010
81007 1994
119513 2007
0 2019
0 2019
0 2019
0 2019
0 2019
118895 2017
48509 2011
100912 2001
95649 1996
0 2019
90495 1994
0 2019
29132 2007
23802 1994
84992 2007
54395 1997
26731 2006
44329 2013
118236 1994
113808 2008
610 2008
0 2019
0 2019
12887 1999
79607 2007
90924 1993
42733 1995
0 2019
0 2019
117714 2016
113885 2011
0 2019
30511 2002
74867 2013
119760 2017
8356 2016
64247 2008
88661 2018
4539 2003
110116 2003
33215 2004
92001 2010
0 2019
81708 

List comprehensions

In [6]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Loops aninhados

In [7]:
dados = [
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]

In [8]:
for lista in dados:
    for item in lista:
        acessorios = np.array(item)
        print(acessorios)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


List comprehensions e sem duplicatas

In [9]:
list(set([item for lista in dados for item in lista]))

['Câmera de estacionamento',
 'Rodas de liga',
 'Central multimídia',
 'Piloto automático',
 'Teto panorâmico',
 'Sensor de chuva',
 'Painel digital',
 'Câmbio automático',
 'Travas elétricas',
 'Controle de estabilidade',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Freios ABS',
 'Vidros elétricos',
 'Sensor crepuscular',
 '4 X 4']

Arrays 2D numpy

In [10]:
acessorios = np.array(dados)
print(acessorios.shape)
print(acessorios)

(3, 8)
[['Rodas de liga' 'Travas elétricas' 'Piloto automático'
  'Bancos de couro' 'Ar condicionado' 'Sensor de estacionamento'
  'Sensor crepuscular' 'Sensor de chuva']
 ['Central multimídia' 'Teto panorâmico' 'Freios ABS' '4 X 4'
  'Painel digital' 'Piloto automático' 'Bancos de couro'
  'Câmera de estacionamento']
 ['Piloto automático' 'Controle de estabilidade' 'Sensor crepuscular'
  'Freios ABS' 'Câmbio automático' 'Bancos de couro' 'Central multimídia'
  'Vidros elétricos']]


Comparando desempenho Numpy e Python list


In [11]:
np_array = np.arange(1000000)
py_list = list(range(1000000))

In [12]:
%time for _ in range(100): np_array *= 2

Wall time: 46.3 ms


In [13]:
#Com list comprehensions
%time for _ in range(100): py_list = [x * 2 for x in py_list]

Wall time: 10.3 s


Observe o tempo de execução da mesma operação com array numpy e python list

Operações simples com array numpy

In [14]:
km_media = km / anos
km_media

array([2.21717424e+01, 2.86891010e+00, 1.86547739e+01, 0.00000000e+00,
       1.28399801e+01, 5.33200795e+00, 0.00000000e+00, 3.86256844e+01,
       4.93517413e+01, 1.88851318e+01, 6.42307692e+00, 4.01195815e+00,
       4.48640680e+01, 0.00000000e+00, 2.06356396e+01, 5.73447421e+01,
       2.30859841e+01, 0.00000000e+00, 1.83958333e+01, 7.52255825e+00,
       5.05459540e+01, 0.00000000e+00, 4.91870612e+01, 5.17122049e+01,
       0.00000000e+00, 0.00000000e+00, 2.87450397e+00, 0.00000000e+00,
       2.93946054e+01, 4.74038172e+01, 1.51041562e+01, 2.67328321e+01,
       8.78097126e+00, 1.69804119e+01, 4.50268123e+01, 2.20426065e+01,
       0.00000000e+00, 0.00000000e+00, 2.75062220e+00, 0.00000000e+00,
       4.64058619e+01, 2.03504743e+01, 0.00000000e+00, 4.31078921e+01,
       0.00000000e+00, 4.87262737e+00, 3.49026946e+01, 1.19690155e+00,
       0.00000000e+00, 4.01143285e+01, 4.25853659e+01, 2.51724826e+01,
       3.38580000e+01, 4.68330010e+01, 1.75845771e+01, 4.06253761e+01,
      

Criando arrays 2D

In [15]:
km_anos_array = np.array([km,anos])
km_anos_array

array([[ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
         99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
         46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
             0,      0,   5795,      0,  58848,  94381,  30163,  53332,
         17720,  33808,  90684,  43975,      0,      0,   5526,      0,
         93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
             0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
        119513,      0,      0,      0,      0,      0, 118895,  48509,
        100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
         54395,  26731,  44329, 118236, 113808,    610,      0,      0,
         12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
             0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
        110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
         26544,  52596,  47503,  89056,  28834, 110564,  56638, 

In [16]:
km_media_array = km_anos_array[0] / (2019 - km_anos_array[1])
km_media_array

<ipython-input-16-3285503826cf>:1: RuntimeWarning: invalid value encountered in true_divide
  km_media_array = km_anos_array[0] / (2019 - km_anos_array[1])


array([2.77562500e+03, 2.04000000e+02, 1.28010345e+03,            nan,
       1.98130769e+03, 1.53257143e+03,            nan, 7.75990000e+03,
       1.10218889e+04, 4.74725000e+03, 7.56411765e+02, 6.71000000e+02,
       4.98738889e+03,            nan, 4.14570000e+03, 3.85356667e+04,
       6.63557143e+03,            nan, 1.23620000e+04, 7.58650000e+03,
       5.95252941e+03,            nan, 3.92316000e+03, 3.67710714e+03,
                  nan,            nan, 1.93166667e+03,            nan,
       3.46164706e+03, 3.37075000e+03, 1.37104545e+03, 2.22216667e+03,
       1.77200000e+04, 1.20742857e+03, 1.81368000e+04, 1.83229167e+03,
                  nan,            nan, 5.52600000e+02,            nan,
       1.55691667e+04, 2.54762500e+03,            nan, 5.07658824e+03,
                  nan, 5.73823529e+02, 4.66300000e+03, 1.33055556e+02,
                  nan, 5.02181250e+03, 8.55540000e+03, 3.88430769e+03,
       3.56400000e+03, 7.22669231e+03, 3.92722222e+03, 3.24028000e+03,
      

OBS: Os resultados nan são as divisões por zero
Observe que a operação foi executada usando as linhas onde se encontram cada dados usado

Atributos no numpy

ndarray.shape

In [17]:
km_anos_array.shape

(2, 258)

ndarray.ndim

In [18]:
km_anos_array.ndim

2

ndarray.T

In [19]:
km_anos_array.T

array([[ 44410,   2003],
       [  5712,   1991],
       [ 37123,   1990],
       [     0,   2019],
       [ 25757,   2006],
       [ 10728,   2012],
       [     0,   2019],
       [ 77599,   2009],
       [ 99197,   2010],
       [ 37978,   2011],
       [ 12859,   2002],
       [  8052,   2007],
       [ 89773,   2001],
       [     0,   2019],
       [ 41457,   2009],
       [115607,   2016],
       [ 46449,   2012],
       [     0,   2019],
       [ 37086,   2016],
       [ 15173,   2017],
       [101193,   2002],
       [     0,   2019],
       [ 98079,   1994],
       [102959,   1991],
       [     0,   2019],
       [     0,   2019],
       [  5795,   2016],
       [     0,   2019],
       [ 58848,   2002],
       [ 94381,   1991],
       [ 30163,   1997],
       [ 53332,   1995],
       [ 17720,   2018],
       [ 33808,   1991],
       [ 90684,   2014],
       [ 43975,   1995],
       [     0,   2019],
       [     0,   2019],
       [  5526,   2009],
       [     0,   2019],


ndarray.tolist() - tranforma array para list

In [20]:
km_anos_array.tolist()

[[44410,
  5712,
  37123,
  0,
  25757,
  10728,
  0,
  77599,
  99197,
  37978,
  12859,
  8052,
  89773,
  0,
  41457,
  115607,
  46449,
  0,
  37086,
  15173,
  101193,
  0,
  98079,
  102959,
  0,
  0,
  5795,
  0,
  58848,
  94381,
  30163,
  53332,
  17720,
  33808,
  90684,
  43975,
  0,
  0,
  5526,
  0,
  93415,
  40762,
  0,
  86302,
  0,
  9755,
  69945,
  2395,
  0,
  80349,
  85554,
  50496,
  67716,
  93947,
  35345,
  81007,
  119513,
  0,
  0,
  0,
  0,
  0,
  118895,
  48509,
  100912,
  95649,
  0,
  90495,
  0,
  29132,
  23802,
  84992,
  54395,
  26731,
  44329,
  118236,
  113808,
  610,
  0,
  0,
  12887,
  79607,
  90924,
  42733,
  0,
  0,
  117714,
  113885,
  0,
  30511,
  74867,
  119760,
  8356,
  64247,
  88661,
  4539,
  110116,
  33215,
  92001,
  0,
  81708,
  70641,
  0,
  91277,
  26544,
  52596,
  47503,
  89056,
  28834,
  110564,
  56638,
  17357,
  74015,
  15196,
  0,
  10821,
  0,
  0,
  9595,
  99052,
  52389,
  119945,
  96005,
  31639,
  0,


ndarray.reshape - Mesmos dados, outra forma (linhas e colunas)

In [21]:
km_anos_array.reshape((43,12), order='F')

array([[ 44410,   2019,  86302,   2001, 117714,   2001,  32017,   2002,
         73914,   1994,  41194,   1996],
       [  2003,  98079,   2002,  95649,   2016,  28834,   1994,   3173,
          2013, 104341,   2005,      0],
       [  5712,   1994,      0,   1996, 113885,   1993,      0,   1996,
        107392,   2001,      0,   2019],
       [  1991, 102959,   2019,      0,   2011, 110564,   2019,  83611,
          1998,  25510,   2019,      0],
       [ 37123,   1991,   9755,   2019,      0,   1995,  56944,   1996,
          9146,   2014,  96100,   2019],
       [  1990,      0,   2002,  90495,   2019,  56638,   1994,  25356,
          2018,  18965,   1997, 112016],
       [     0,   2019,  69945,   1994,  30511,   2003,      0,   2015,
             0,   1996, 103900,   2014],
       [  2019,      0,   2004,      0,   2002,  17357,   2019,  88634,
          2019,  87161,   1990,  91840],
       [ 25757,   2019,   2395,   2019,  74867,   2014,  86519,   1993,
         17924,   1993, 

ndarray.reshape - Copia dos dados

In [22]:
km_anos_array = np.array(km_anos_array).reshape((43,12), order='F')
km_anos_array_new = km_media_array.copy()
km_anos_array_new

array([2.77562500e+03, 2.04000000e+02, 1.28010345e+03,            nan,
       1.98130769e+03, 1.53257143e+03,            nan, 7.75990000e+03,
       1.10218889e+04, 4.74725000e+03, 7.56411765e+02, 6.71000000e+02,
       4.98738889e+03,            nan, 4.14570000e+03, 3.85356667e+04,
       6.63557143e+03,            nan, 1.23620000e+04, 7.58650000e+03,
       5.95252941e+03,            nan, 3.92316000e+03, 3.67710714e+03,
                  nan,            nan, 1.93166667e+03,            nan,
       3.46164706e+03, 3.37075000e+03, 1.37104545e+03, 2.22216667e+03,
       1.77200000e+04, 1.20742857e+03, 1.81368000e+04, 1.83229167e+03,
                  nan,            nan, 5.52600000e+02,            nan,
       1.55691667e+04, 2.54762500e+03,            nan, 5.07658824e+03,
                  nan, 5.73823529e+02, 4.66300000e+03, 1.33055556e+02,
                  nan, 5.02181250e+03, 8.55540000e+03, 3.88430769e+03,
       3.56400000e+03, 7.22669231e+03, 3.92722222e+03, 3.24028000e+03,
      

Refcheck - para manipular os dados (adicionar)


In [25]:
km_anos_array_new.resize((44,12), refcheck=False)
km_anos_array_new

array([[2.77562500e+03, 2.04000000e+02, 1.28010345e+03,            nan,
        1.98130769e+03, 1.53257143e+03,            nan, 7.75990000e+03,
        1.10218889e+04, 4.74725000e+03, 7.56411765e+02, 6.71000000e+02],
       [4.98738889e+03,            nan, 4.14570000e+03, 3.85356667e+04,
        6.63557143e+03,            nan, 1.23620000e+04, 7.58650000e+03,
        5.95252941e+03,            nan, 3.92316000e+03, 3.67710714e+03],
       [           nan,            nan, 1.93166667e+03,            nan,
        3.46164706e+03, 3.37075000e+03, 1.37104545e+03, 2.22216667e+03,
        1.77200000e+04, 1.20742857e+03, 1.81368000e+04, 1.83229167e+03],
       [           nan,            nan, 5.52600000e+02,            nan,
        1.55691667e+04, 2.54762500e+03,            nan, 5.07658824e+03,
                   nan, 5.73823529e+02, 4.66300000e+03, 1.33055556e+02],
       [           nan, 5.02181250e+03, 8.55540000e+03, 3.88430769e+03,
        3.56400000e+03, 7.22669231e+03, 3.92722222e+03, 3.24

Estatísticas com Numpy

In [24]:
file_name3 = os.path.join('./data/', "carros-valor.txt")

anos = np.loadtxt(file_name2, dtype=int)
km = np.loadtxt(file_name1, dtype=int)
valor = np.loadtxt(file_name3)

In [27]:
dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

Média dos elementos - np.mean()

In [30]:
#por coluna
np.mean(dataset, axis= 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

Desvio Padrão

In [31]:
np.std(dataset, axis=0)

array([9.70703915e+00, 3.98598270e+04, 2.97541012e+04])